name: Update Nodes Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点自动运行
  workflow_dispatch:      # 支持手动触发

jobs:
  update-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 禁用默认凭据，避免冲突

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run conversion script
        run: python convert.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add nodes.txt
          git commit -m "自动更新节点备注 ⏰" || echo "No changes to commit"
          # 使用 GITHUB_TOKEN 认证 push，避免密码问题
          git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${GITHUB_REF##*/}
